re_main:
    path:     /{_locale}/site
    defaults: { _controller: MainBundle:Default:index ,_locale: fr }
    requirements:
        _locale: en|fr
re_test:
    path:     /test
    defaults: { _controller: MainBundle:Default:test } 